# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8a69bdfb9116d50d9bdf31cd8ef92d0ceaa0c0e21b3f21761ffa8e6034b6743718ee83297edd1f645c98d3b3cf92638461adba97833c58055ae690d53003290

test:
  secret_key_base: f051832f2d528664063f2d9e26ebc309623ffddac51a1ef32850e565f166c117c9c79a788fa328a849a16a27bf657d29cbc7f1a4b50fc98840a06b6328ad6d00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
